version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::884202029588:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1SKRN07ZLV6A7"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::884202029588:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1N5Y02KFOREG0"
cloudformation_execution_role = "arn:aws:iam::884202029588:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-2TKOVYU3L4WK"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-iwsgnwyzkre9"
image_repository = "884202029588.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-mokfdoh44jlo"
region = "us-east-1"
